// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
	BirthDate   *string `json:"birth_date"`
	PhoneNumber *string `json:"phone_number"`
	Photo       *string `json:"photo"`
	Gender      *string `json:"gender"`
	Address     *string `json:"address"`
}

type ResponseLogin struct {
	Code  int    `json:"code"`
	Token string `json:"token"`
}

type ResponseMessage struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type User struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
	BirthDate   *string `json:"birth_date"`
	PhoneNumber *string `json:"phone_number"`
	Photo       *string `json:"photo"`
	Gender      *string `json:"gender"`
	Address     *string `json:"address"`
}
